#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kassasys
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dbkassa")]
	public partial class DatabaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertklanten(klanten instance);
    partial void Updateklanten(klanten instance);
    partial void Deleteklanten(klanten instance);
    partial void Insertproduct_soorten(product_soorten instance);
    partial void Updateproduct_soorten(product_soorten instance);
    partial void Deleteproduct_soorten(product_soorten instance);
    partial void Insertprijshistory(prijshistory instance);
    partial void Updateprijshistory(prijshistory instance);
    partial void Deleteprijshistory(prijshistory instance);
    partial void Insertbestellingen(bestellingen instance);
    partial void Updatebestellingen(bestellingen instance);
    partial void Deletebestellingen(bestellingen instance);
    partial void Insertbestelitem(bestelitem instance);
    partial void Updatebestelitem(bestelitem instance);
    partial void Deletebestelitem(bestelitem instance);
    partial void Insertproducten(producten instance);
    partial void Updateproducten(producten instance);
    partial void Deleteproducten(producten instance);
    #endregion
		
		public DatabaseDataContext() : 
				base(global::Kassasys.Properties.Settings.Default.dbkassaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<klanten> klantens
		{
			get
			{
				return this.GetTable<klanten>();
			}
		}
		
		public System.Data.Linq.Table<product_soorten> product_soortens
		{
			get
			{
				return this.GetTable<product_soorten>();
			}
		}
		
		public System.Data.Linq.Table<prijshistory> prijshistories
		{
			get
			{
				return this.GetTable<prijshistory>();
			}
		}
		
		public System.Data.Linq.Table<bestellingen> bestellingens
		{
			get
			{
				return this.GetTable<bestellingen>();
			}
		}
		
		public System.Data.Linq.Table<bestelitem> bestelitems
		{
			get
			{
				return this.GetTable<bestelitem>();
			}
		}
		
		public System.Data.Linq.Table<producten> productens
		{
			get
			{
				return this.GetTable<producten>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.klanten")]
	public partial class klanten : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _voornaam;
		
		private string _achternaam;
		
		private string _woonplaats;
		
		private string _telefoonnummer;
		
		private string _email;
		
		private EntitySet<bestellingen> _bestellingens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnvoornaamChanging(string value);
    partial void OnvoornaamChanged();
    partial void OnachternaamChanging(string value);
    partial void OnachternaamChanged();
    partial void OnwoonplaatsChanging(string value);
    partial void OnwoonplaatsChanged();
    partial void OntelefoonnummerChanging(string value);
    partial void OntelefoonnummerChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    #endregion
		
		public klanten()
		{
			this._bestellingens = new EntitySet<bestellingen>(new Action<bestellingen>(this.attach_bestellingens), new Action<bestellingen>(this.detach_bestellingens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_voornaam", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string voornaam
		{
			get
			{
				return this._voornaam;
			}
			set
			{
				if ((this._voornaam != value))
				{
					this.OnvoornaamChanging(value);
					this.SendPropertyChanging();
					this._voornaam = value;
					this.SendPropertyChanged("voornaam");
					this.OnvoornaamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_achternaam", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string achternaam
		{
			get
			{
				return this._achternaam;
			}
			set
			{
				if ((this._achternaam != value))
				{
					this.OnachternaamChanging(value);
					this.SendPropertyChanging();
					this._achternaam = value;
					this.SendPropertyChanged("achternaam");
					this.OnachternaamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_woonplaats", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string woonplaats
		{
			get
			{
				return this._woonplaats;
			}
			set
			{
				if ((this._woonplaats != value))
				{
					this.OnwoonplaatsChanging(value);
					this.SendPropertyChanging();
					this._woonplaats = value;
					this.SendPropertyChanged("woonplaats");
					this.OnwoonplaatsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefoonnummer", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string telefoonnummer
		{
			get
			{
				return this._telefoonnummer;
			}
			set
			{
				if ((this._telefoonnummer != value))
				{
					this.OntelefoonnummerChanging(value);
					this.SendPropertyChanging();
					this._telefoonnummer = value;
					this.SendPropertyChanged("telefoonnummer");
					this.OntelefoonnummerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="klanten_bestellingen", Storage="_bestellingens", ThisKey="id", OtherKey="klant_id")]
		public EntitySet<bestellingen> bestellingens
		{
			get
			{
				return this._bestellingens;
			}
			set
			{
				this._bestellingens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_bestellingens(bestellingen entity)
		{
			this.SendPropertyChanging();
			entity.klanten = this;
		}
		
		private void detach_bestellingens(bestellingen entity)
		{
			this.SendPropertyChanging();
			entity.klanten = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.product_soorten")]
	public partial class product_soorten : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _soort;
		
		private EntitySet<producten> _productens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnsoortChanging(string value);
    partial void OnsoortChanged();
    #endregion
		
		public product_soorten()
		{
			this._productens = new EntitySet<producten>(new Action<producten>(this.attach_productens), new Action<producten>(this.detach_productens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soort", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string soort
		{
			get
			{
				return this._soort;
			}
			set
			{
				if ((this._soort != value))
				{
					this.OnsoortChanging(value);
					this.SendPropertyChanging();
					this._soort = value;
					this.SendPropertyChanged("soort");
					this.OnsoortChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="product_soorten_producten", Storage="_productens", ThisKey="id", OtherKey="ps_id")]
		public EntitySet<producten> productens
		{
			get
			{
				return this._productens;
			}
			set
			{
				this._productens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_productens(producten entity)
		{
			this.SendPropertyChanging();
			entity.product_soorten = this;
		}
		
		private void detach_productens(producten entity)
		{
			this.SendPropertyChanging();
			entity.product_soorten = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.prijshistories")]
	public partial class prijshistory : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.DateTime _start_datum;
		
		private System.DateTime _eind_datum;
		
		private decimal _prijs;
		
		private int _product_id;
		
		private EntityRef<producten> _producten;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onstart_datumChanging(System.DateTime value);
    partial void Onstart_datumChanged();
    partial void Oneind_datumChanging(System.DateTime value);
    partial void Oneind_datumChanged();
    partial void OnprijsChanging(decimal value);
    partial void OnprijsChanged();
    partial void Onproduct_idChanging(int value);
    partial void Onproduct_idChanged();
    #endregion
		
		public prijshistory()
		{
			this._producten = default(EntityRef<producten>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_start_datum", DbType="DateTime NOT NULL")]
		public System.DateTime start_datum
		{
			get
			{
				return this._start_datum;
			}
			set
			{
				if ((this._start_datum != value))
				{
					this.Onstart_datumChanging(value);
					this.SendPropertyChanging();
					this._start_datum = value;
					this.SendPropertyChanged("start_datum");
					this.Onstart_datumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eind_datum", DbType="DateTime NOT NULL")]
		public System.DateTime eind_datum
		{
			get
			{
				return this._eind_datum;
			}
			set
			{
				if ((this._eind_datum != value))
				{
					this.Oneind_datumChanging(value);
					this.SendPropertyChanging();
					this._eind_datum = value;
					this.SendPropertyChanged("eind_datum");
					this.Oneind_datumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prijs", DbType="Money NOT NULL")]
		public decimal prijs
		{
			get
			{
				return this._prijs;
			}
			set
			{
				if ((this._prijs != value))
				{
					this.OnprijsChanging(value);
					this.SendPropertyChanging();
					this._prijs = value;
					this.SendPropertyChanged("prijs");
					this.OnprijsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_id", DbType="Int NOT NULL")]
		public int product_id
		{
			get
			{
				return this._product_id;
			}
			set
			{
				if ((this._product_id != value))
				{
					if (this._producten.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onproduct_idChanging(value);
					this.SendPropertyChanging();
					this._product_id = value;
					this.SendPropertyChanged("product_id");
					this.Onproduct_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="producten_prijshistory", Storage="_producten", ThisKey="product_id", OtherKey="id", IsForeignKey=true)]
		public producten producten
		{
			get
			{
				return this._producten.Entity;
			}
			set
			{
				producten previousValue = this._producten.Entity;
				if (((previousValue != value) 
							|| (this._producten.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._producten.Entity = null;
						previousValue.prijshistories.Remove(this);
					}
					this._producten.Entity = value;
					if ((value != null))
					{
						value.prijshistories.Add(this);
						this._product_id = value.id;
					}
					else
					{
						this._product_id = default(int);
					}
					this.SendPropertyChanged("producten");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.bestellingen")]
	public partial class bestellingen : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.DateTime _datum;
		
		private int _klant_id;
		
		private EntitySet<bestelitem> _bestelitems;
		
		private EntityRef<klanten> _klanten;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OndatumChanging(System.DateTime value);
    partial void OndatumChanged();
    partial void Onklant_idChanging(int value);
    partial void Onklant_idChanged();
    #endregion
		
		public bestellingen()
		{
			this._bestelitems = new EntitySet<bestelitem>(new Action<bestelitem>(this.attach_bestelitems), new Action<bestelitem>(this.detach_bestelitems));
			this._klanten = default(EntityRef<klanten>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datum", DbType="DateTime NOT NULL")]
		public System.DateTime datum
		{
			get
			{
				return this._datum;
			}
			set
			{
				if ((this._datum != value))
				{
					this.OndatumChanging(value);
					this.SendPropertyChanging();
					this._datum = value;
					this.SendPropertyChanged("datum");
					this.OndatumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_klant_id", DbType="Int NOT NULL")]
		public int klant_id
		{
			get
			{
				return this._klant_id;
			}
			set
			{
				if ((this._klant_id != value))
				{
					if (this._klanten.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onklant_idChanging(value);
					this.SendPropertyChanging();
					this._klant_id = value;
					this.SendPropertyChanged("klant_id");
					this.Onklant_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="bestellingen_bestelitem", Storage="_bestelitems", ThisKey="id", OtherKey="bestelling_id")]
		public EntitySet<bestelitem> bestelitems
		{
			get
			{
				return this._bestelitems;
			}
			set
			{
				this._bestelitems.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="klanten_bestellingen", Storage="_klanten", ThisKey="klant_id", OtherKey="id", IsForeignKey=true)]
		public klanten klanten
		{
			get
			{
				return this._klanten.Entity;
			}
			set
			{
				klanten previousValue = this._klanten.Entity;
				if (((previousValue != value) 
							|| (this._klanten.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._klanten.Entity = null;
						previousValue.bestellingens.Remove(this);
					}
					this._klanten.Entity = value;
					if ((value != null))
					{
						value.bestellingens.Add(this);
						this._klant_id = value.id;
					}
					else
					{
						this._klant_id = default(int);
					}
					this.SendPropertyChanged("klanten");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_bestelitems(bestelitem entity)
		{
			this.SendPropertyChanging();
			entity.bestellingen = this;
		}
		
		private void detach_bestelitems(bestelitem entity)
		{
			this.SendPropertyChanging();
			entity.bestellingen = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.bestelitems")]
	public partial class bestelitem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _aantal;
		
		private int _bestelling_id;
		
		private int _product_id;
		
		private EntityRef<bestellingen> _bestellingen;
		
		private EntityRef<producten> _producten;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnaantalChanging(int value);
    partial void OnaantalChanged();
    partial void Onbestelling_idChanging(int value);
    partial void Onbestelling_idChanged();
    partial void Onproduct_idChanging(int value);
    partial void Onproduct_idChanged();
    #endregion
		
		public bestelitem()
		{
			this._bestellingen = default(EntityRef<bestellingen>);
			this._producten = default(EntityRef<producten>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aantal", DbType="Int NOT NULL")]
		public int aantal
		{
			get
			{
				return this._aantal;
			}
			set
			{
				if ((this._aantal != value))
				{
					this.OnaantalChanging(value);
					this.SendPropertyChanging();
					this._aantal = value;
					this.SendPropertyChanged("aantal");
					this.OnaantalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bestelling_id", DbType="Int NOT NULL")]
		public int bestelling_id
		{
			get
			{
				return this._bestelling_id;
			}
			set
			{
				if ((this._bestelling_id != value))
				{
					if (this._bestellingen.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onbestelling_idChanging(value);
					this.SendPropertyChanging();
					this._bestelling_id = value;
					this.SendPropertyChanged("bestelling_id");
					this.Onbestelling_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_id", DbType="Int NOT NULL")]
		public int product_id
		{
			get
			{
				return this._product_id;
			}
			set
			{
				if ((this._product_id != value))
				{
					if (this._producten.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onproduct_idChanging(value);
					this.SendPropertyChanging();
					this._product_id = value;
					this.SendPropertyChanged("product_id");
					this.Onproduct_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="bestellingen_bestelitem", Storage="_bestellingen", ThisKey="bestelling_id", OtherKey="id", IsForeignKey=true)]
		public bestellingen bestellingen
		{
			get
			{
				return this._bestellingen.Entity;
			}
			set
			{
				bestellingen previousValue = this._bestellingen.Entity;
				if (((previousValue != value) 
							|| (this._bestellingen.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._bestellingen.Entity = null;
						previousValue.bestelitems.Remove(this);
					}
					this._bestellingen.Entity = value;
					if ((value != null))
					{
						value.bestelitems.Add(this);
						this._bestelling_id = value.id;
					}
					else
					{
						this._bestelling_id = default(int);
					}
					this.SendPropertyChanged("bestellingen");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="producten_bestelitem", Storage="_producten", ThisKey="product_id", OtherKey="id", IsForeignKey=true)]
		public producten producten
		{
			get
			{
				return this._producten.Entity;
			}
			set
			{
				producten previousValue = this._producten.Entity;
				if (((previousValue != value) 
							|| (this._producten.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._producten.Entity = null;
						previousValue.bestelitems.Remove(this);
					}
					this._producten.Entity = value;
					if ((value != null))
					{
						value.bestelitems.Add(this);
						this._product_id = value.id;
					}
					else
					{
						this._product_id = default(int);
					}
					this.SendPropertyChanged("producten");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.producten")]
	public partial class producten : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _naam;
		
		private int _ps_id;
		
		private string _barcode;
		
		private EntitySet<prijshistory> _prijshistories;
		
		private EntitySet<bestelitem> _bestelitems;
		
		private EntityRef<product_soorten> _product_soorten;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnaamChanging(string value);
    partial void OnnaamChanged();
    partial void Onps_idChanging(int value);
    partial void Onps_idChanged();
    partial void OnbarcodeChanging(string value);
    partial void OnbarcodeChanged();
    #endregion
		
		public producten()
		{
			this._prijshistories = new EntitySet<prijshistory>(new Action<prijshistory>(this.attach_prijshistories), new Action<prijshistory>(this.detach_prijshistories));
			this._bestelitems = new EntitySet<bestelitem>(new Action<bestelitem>(this.attach_bestelitems), new Action<bestelitem>(this.detach_bestelitems));
			this._product_soorten = default(EntityRef<product_soorten>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_naam", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string naam
		{
			get
			{
				return this._naam;
			}
			set
			{
				if ((this._naam != value))
				{
					this.OnnaamChanging(value);
					this.SendPropertyChanging();
					this._naam = value;
					this.SendPropertyChanged("naam");
					this.OnnaamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ps_id", DbType="Int NOT NULL")]
		public int ps_id
		{
			get
			{
				return this._ps_id;
			}
			set
			{
				if ((this._ps_id != value))
				{
					if (this._product_soorten.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onps_idChanging(value);
					this.SendPropertyChanging();
					this._ps_id = value;
					this.SendPropertyChanged("ps_id");
					this.Onps_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_barcode", DbType="VarChar(128)")]
		public string barcode
		{
			get
			{
				return this._barcode;
			}
			set
			{
				if ((this._barcode != value))
				{
					this.OnbarcodeChanging(value);
					this.SendPropertyChanging();
					this._barcode = value;
					this.SendPropertyChanged("barcode");
					this.OnbarcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="producten_prijshistory", Storage="_prijshistories", ThisKey="id", OtherKey="product_id")]
		public EntitySet<prijshistory> prijshistories
		{
			get
			{
				return this._prijshistories;
			}
			set
			{
				this._prijshistories.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="producten_bestelitem", Storage="_bestelitems", ThisKey="id", OtherKey="product_id")]
		public EntitySet<bestelitem> bestelitems
		{
			get
			{
				return this._bestelitems;
			}
			set
			{
				this._bestelitems.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="product_soorten_producten", Storage="_product_soorten", ThisKey="ps_id", OtherKey="id", IsForeignKey=true)]
		public product_soorten product_soorten
		{
			get
			{
				return this._product_soorten.Entity;
			}
			set
			{
				product_soorten previousValue = this._product_soorten.Entity;
				if (((previousValue != value) 
							|| (this._product_soorten.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._product_soorten.Entity = null;
						previousValue.productens.Remove(this);
					}
					this._product_soorten.Entity = value;
					if ((value != null))
					{
						value.productens.Add(this);
						this._ps_id = value.id;
					}
					else
					{
						this._ps_id = default(int);
					}
					this.SendPropertyChanged("product_soorten");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_prijshistories(prijshistory entity)
		{
			this.SendPropertyChanging();
			entity.producten = this;
		}
		
		private void detach_prijshistories(prijshistory entity)
		{
			this.SendPropertyChanging();
			entity.producten = null;
		}
		
		private void attach_bestelitems(bestelitem entity)
		{
			this.SendPropertyChanging();
			entity.producten = this;
		}
		
		private void detach_bestelitems(bestelitem entity)
		{
			this.SendPropertyChanging();
			entity.producten = null;
		}
	}
}
#pragma warning restore 1591
